### ISSUE TITLE
Markdown: __map_ parameters

### ISSUE THREAD

**Issue by christophfroehlich** [PickNikRobotics/generate_parameter_library#118]
I kindly submit a feature request for the markdown generation 😇

-  `__map_ ` : these ones are completely ignored now

My understanding of the python/jinja scripts is too low. But if someone points me in the direction I could help to implement these.

**Comment by tylerjw** [comment]
@christophfroehlich thank you for the issue. I don't clearly understand your first point. Would you mind breaking it into a separate issue and leaving this about the non-support for map. I don't have time to work on this now but will happily accept PRs that fix this. I'll try to find some time to better document the python/jinja so it is easier to modify for you. I too struggle to edit it efficiently and some better design documentation would be good for me to write because it would force me to finally learn the little details.

**Comment by christophfroehlich** [comment]
@tylerjw see #126 for a more detailed explanation of my problem with the nested structures. 
Regarding the map parameters here: Somethink like we have with the[ JTC docs ](https://control.ros.org/master/doc/ros2_controllers/joint_trajectory_controller/doc/userdoc.html)would be good enough:

![image](https://github.com/PickNikRobotics/generate_parameter_library/assets/3367244/00ed7c62-9df3-4eab-bd90-e73970b3f089)
